# Generated by Django 3.2.5 on 2021-09-24 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_operateuser_keyuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operateuser',
            name='keyTagPlace',
        ),
        migrations.RemoveField(
            model_name='operateuser',
            name='password',
        ),
    ]
