# Generated by Django 3.2.5 on 2021-10-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_memomain_boolhasmodified'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoMainBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyMemoId', models.IntegerField(verbose_name='メモID')),
                ('dateUpdate', models.DateField(verbose_name='更新日時')),
                ('charBackUpText', models.TextField(verbose_name='元の文')),
            ],
        ),
    ]
