# Generated by Django 3.2.5 on 2021-10-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_memomainbackup'),
    ]

    operations = [
        migrations.AddField(
            model_name='memomainbackup',
            name='typeBackUpCase',
            field=models.CharField(default='none', max_length=20, verbose_name='バックアップ種類'),
        ),
    ]
