# Generated by Django 3.2.5 on 2021-10-28 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_memomain_boolhasdelete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memomain',
            old_name='boolHasDelete',
            new_name='boolHasDeleted',
        ),
    ]
