# Generated by Django 3.2.5 on 2021-11-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_boolhasdelete_memomain_boolhasdeleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='operateuser',
            name='numRank',
            field=models.IntegerField(default=1, verbose_name='ランク'),
        ),
    ]
