# Generated by Django 3.2.5 on 2021-11-10 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_operateuser_numrank'),
    ]

    operations = [
        migrations.AddField(
            model_name='taginformatedmemo',
            name='keyFacility',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.facility', verbose_name='利用施設'),
        ),
        migrations.AlterField(
            model_name='tagmain',
            name='datePublish',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登録日'),
        ),
    ]
