# Generated by Django 3.2.5 on 2021-12-11 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_auto_20211110_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMakePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boolIsDone', models.BooleanField(default=False, verbose_name='登録待ちフラグ')),
                ('keyUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='待機ユーザ')),
            ],
        ),
    ]
