
#数字に変換された意味を登録しておく
NUM_TAGTYPE_MEMBER=2
NUM_TAGTYPE_GUEST=3

NUM_COMMON_TAG_FACILITY=1

NUM_TAG_STATUS_MAINLIST=1
NUM_TAG_STATUS_SUBLIST=2
NUM_TAG_STATUS_SEARCHONLY=3
NUM_TAG_STATUS_NEVER_IN_LIST=4

NUM_MEMO_TYPE_FREE=1
NUM_MEMO_TYPE_FORMATTED=2

NUM_USER_HAS_CHANGE_AUTH=3
NUM_USER_IS_MEMBER=2
NUM_USER_IS_OWNER=4

NUM_STATUS_ENROLL=1 #在職
NUM_STATUS_RETIRE=2 #休職
NUM_STATUS_LEAVE=3 #退職

NUM_USER_RANK_ADMIN=100
NUM_USER_RANK_LEADER=10
NUM_USER_RANK_MEMBER=1
